name: Download Python Image
on: workflow_dispatch # 手动触发

jobs:
  download-python:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Python Image
        run: |
          # 这里拉取 python:3.11-slim
          docker pull python:3.11-slim

      - name: Save Image to Tar
        run: |
          # 导出为 tar 文件，文件名叫 python_slim.tar
          docker save -o python_slim.tar python:3.11-slim

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # 最后生成的压缩包名字
          name: python-3.11-slim-pkg
          path: python_slim.tar
          retention-days: 1
